questions =  [
    {"id": 0, "question": "La produttività è il miglior modo con cui una società possa prosperare.", "effects": {"right": 1}},
    {"id": 1, "question": "La beneficienza è un modo migliore di aiutare i bisognosi rispetto all'assistenza sociale.", "effects": {"right": 1}},
    {"id": 2, "question": "Il CCNL distorce il mercato del lavoro, sarebbe più corretto e giusto eliminare ogni forma di lavoro dipendente, in favore di contratti più flessibili.", "effects": {"right": 1}},
    {"id": 3, "question": "Il genere umano è avido per natura.", "effects": {"right": 1}},
    {"id": 4, "question": "\"Sfruttamento\" è un termine superato, dato che le lotte del capitalismo del 1800 non esistono più.", "effects": {"right": 1}},
    {"id": 5, "question": "Il comunismo è un ideale che non potrà mai funzionare nella pratica.", "effects": {"right": 1}},
    {"id": 6, "question": "Lo stato non si può reggere solo sulla tassazione dei più ricchi.", "effects": {"right": 1}},
    {"id": 7, "question": "Meglio si lavora, più si hanno possibilità di progredire nella scala sociale.", "effects": {"right": 1}},
    {"id": 8, "question": "La regolamentazione è sempre una buona cosa", "effects": {"right": -1}},
    {"id": 9, "question": "\“Il governo deve provvedere a tutti\” è un'idea intrinsecamente buona.", "effects": {"right": -1}},
    {"id": 10, "question": "Le diseguaglianze si combattono solo ed esclusivamente con il welfare.", "effects": {"right": -1}},
    {"id": 11, "question": "Nessuno dovrebbe avere proprietà terriere.", "effects": {"right": -1}},
    {"id": 12, "question": "Tutte le aziende e organizzazioni dovrebbero essere nazionalizzate.", "effects": {"right": -1}},
    {"id": 13, "question": "Le classi di reddito sono la prima divisione della società.", "effects": {"right": -1}},
    {"id": 14, "question": "Nel mondo le diseguaglianze sono troppo alte, sia in termini assoluti, che in termini relativi, inoltre queste a livello mondiale aumentano da sempre.", "effects": {"right": -1}},
    {"id": 15, "question": "A volte è giusto che il governo possa spiare i suoi cittadini per combattere estremisti e terroristi.", "effects": {"auth": 1}},
    {"id": 16, "question": "Un governo autoritario dotato di una moralità salda è una soluzione più efficiente ed efficace rispetto alla democrazia.", "effects": {"auth": 1}},
    {"id": 17, "question": "Un governo può avere successo solo attraverso l’uso della forza.", "effects": {"auth": 1}},
    {"id": 18, "question": "Solo il governo può regolare in modo equo ed efficace le organizzazioni.", "effects": {"auth": 1}},
    {"id": 19, "question": "La lentezza della burocrazia è un costo necessario.", "effects": {"auth": 1}},
    {"id": 20, "question": "In tempi di crisi, la sicurezza diventa più importante delle libertà civili.", "effects": {"auth": 1}},
    {"id": 21, "question": "Se non hai nulla da nascondere, non hai nulla da temere. ", "effects": {"auth": 1}},
    {"id": 22, "question": "Tutte le droghe dovrebbero essere liberalizzate, anche quelle pesanti", "effects": {"auth": -1}},
    {"id": 23, "question": "Senza democrazia la società non è nulla", "effects": {"auth": -1}},
    {"id": 24, "question": "Più il potere statale è decentralizzato meglio è.", "effects": {"auth": -1}},
    {"id": 25, "question": "Il governo dovrebbe, al massimo, fornire servizi di emergenza e forze dell'ordine.", "effects": {"auth": -1}},
    {"id": 26, "question": "Le forze dell’ordine nel mondo sono uno dei mezzi con cui i governi mantengono lo status-quo.", "effects": {"auth": -1}},
    {"id": 27, "question": "Le scuole statali sono un mezzo di propaganda politica.", "effects": {"auth": -1}},
    {"id": 28, "question": "La prostituzione dovrebbe essere legale.", "effects": {"prog": 1}},
    {"id": 29, "question": "Ogni individuo dovrebbe disporre del proprio corpo come meglio ritiene.", "effects": {"prog": 1}},
    {"id": 30, "question": "La religione è l’oppio dei popoli", "effects": {"prog": 1}},
    {"id": 31, "question": "Le pratiche sessuali estreme, come il BDSM (Bondage, disciplina, dominazione, sottomissione, sadismo, masochismo), non sono affare dello stato, ma appartengono alle scelte individuali del singolo", "effects": {"prog": 1}},
    {"id": 32, "question": "Tutti dovrebbero essere vegani. Mangiare un animale è immorale e dovrebbe essere vietato dallo stato.", "effects": {"prog": 1}},
    {"id": 33, "question": "Il genere (uomo, donna) è un costrutto sociale che dovrebbe essere eliminato, anche dal punto di vista burocratico.", "effects": {"prog": 1}},
    {"id": 34, "question": "La morale dell’individuo è più importante della cultura della società.", "effects": {"prog": 1}},
    {"id": 35, "question": "", "effects": {"prog": 1}},
    {"id": 36, "question": "L'omosessualità è contro i miei valori.", "effects": {"prog": -1}},
    {"id": 37, "question": "Solo le persone eterossessuali dovrebbero poter adottare bambini.", "effects": {"prog": -1}},
    {"id": 38, "question": "La pena di morte dovrebbe esistere per certi crimini.", "effects": {"prog": -1}},
    {"id": 39, "question": "Non si può essere morali senza religione.", "effects": {"prog": -1}},
    {"id": 40, "question": "I genitori dovrebbero avere il potere assoluto sui propri figli in quanto sono di loro proprietà.", "effects": {"prog": -1}},
    {"id": 41, "question": "La diversità culturale è un male.", "effects": {"prog": -1}}
];
