
questions =  [
    {"id": 0, "question": "La produttività è il miglior modo con cui una società possa prosperare.", "effects": {"right": 1}},
    {"id": 1, "question": "La beneficienza è un modo migliore di aiutare i poveri rispetto all'assistenza sociale.", "effects": {"right": 1}},
    {"id": 2, "question": "Il CCNL distorce il mercato del lavoro, sarebbe più corretto e giusto eliminare ogni forma di lavoro dipendente, in favore di contratti più flessibili.", "effects": {"right": 1}},
    {"id": 3, "question": "Il genere umano è avido e accidioso per natura.", "effects": {"right": 1}},
    {"id": 4, "question": "Il comunismo è un ideale che non potrà mai funzionare nella pratica.", "effects": {"right": 1}},
    {"id": 5, "question": "In Italia la pressione fiscale è talmente elevata che tassare ulteriormente il patrimonio sarebbe controproducente", "effects": {"right": 1}},
    {"id": 6, "question": "Meglio si lavora, più si hanno possibilità di progredire nella scala sociale, a prescindere dal reddito percepito.", "effects": {"right": 1}},
    {"id": 7, "question": "Le diseguaglianze si combattono solo ed esclusivamente con l’assistenzialismo", "effects": {"right": -1}},
    {"id": 8, "question": "Alcuni beni e servizi dovrebbero essere gestiti solo dallo stato.", "effects": {"right": -1}},
    {"id": 9, "question": "Alitalia rappresenta un buon investimento, non necessariamente economico, per lo stato e per i suoi cittadini", "effects": {"right": -1}},
    {"id": 10, "question": "Le classi di reddito sono la prima divisione della società.", "effects": {"right": -1}},
    {"id": 11, "question": "Nel mondo le diseguaglianze sono troppo alte, sia in termini assoluti, che in termini relativi, inoltre queste a livello mondiale aumentano da sempre.", "effects": {"right": -1}},
    {"id": 12, "question": "Il mondo del lavoro dovrebbe essere categorizzato in base al sesso, infatti le donne eccellono in mansioni proprie delle stesse, ed è quindi sbagliato incentivare l’uno o l’altro sesso verso lavori verso in cui non hanno affinità", "effects": {"auth": 1}},
    {"id": 13, "question": "Un governo autoritario dotato di una moralità salda è una soluzione più efficiente ed efficace rispetto alla democrazia.", "effects": {"auth": 1}},
    {"id": 14, "question": "Il potere va gestito secondo i precetti di Macchiavelli espressi nel De Principatibus": {"auth": 1}},
    {"id": 15, "question": "Solo il governo può regolare in modo equo ed efficace le organizzazioni.", "effects": {"auth": 1}},
    {"id": 16, "question": "La lentezza della burocrazia è un costo necessario.", "effects": {"auth": 1}},
    {"id": 17, "question": "In tempi di crisi, la sicurezza diventa più importante delle libertà civili.", "effects": {"auth": 1}},
    {"id": 18, "question": "Il caso Snowden ci fa capire quanto sia importante dotarsi di un organo centrale che definisca come debbano essere gestiti i dati delle persone ", "effects": {"auth": 1}},
    {"id": 19, "question": "Non esistono droghe leggere o pesanti, esiste la libertà di scelta", "effects": {"auth": -1}},
    {"id": 20, "question": "Senza democrazia la libertà non è nulla", "effects": {"auth": -1}},
    {"id": 21, "question": "Più il potere statale è decentralizzato meglio è.", "effects": {"auth": -1}},
    {"id": 22, "question": "Il governo dovrebbe, al massimo, fornire servizi di emergenza e forze dell'ordine.", "effects": {"auth": -1}},
    {"id": 23, "question": "Le forze dell’ordine nel mondo sono uno dei mezzi con cui i governi mantengono lo status-quo.", "effects": {"auth": -1}},
    {"id": 24, "question": "Le scuole statali sono un mezzo di propaganda politica.", "effects": {"auth": -1}},
    {"id": 25, "question": "La prostituzione dovrebbe essere legale e incentivata dallo stato.", "effects": {"prog": 1}},
    {"id": 26, "question": "L’eutanasia è un diritto": {"prog": 1}},
    {"id": 27, "question": "La religione è l’oppio dei popoli", "effects": {"prog": 1}},
    {"id": 28, "question": "Le pratiche sessuali estreme, come il BDSM (Bondage, disciplina, dominazione, sottomissione, sadismo, masochismo), non sono affare dello stato, ma appartengono alle scelte individuali del singolo", "effects": {"prog": 1}},
    {"id": 29, "question": "Tutti dovrebbero essere vegani. Mangiare un animale è immorale e dovrebbe essere vietato dallo stato.", "effects": {"prog": 1}},
    {"id": 30, "question": "Il genere (uomo, donna) è un costrutto sociale che dovrebbe essere eliminato, anche dal punto di vista burocratico.", "effects": {"prog": 1}},
    {"id": 31, "question": "La morale dell’individuo è più importante della cultura della società.", "effects": {"prog": 1}},
    {"id": 32, "question": "L'omosessualità è contro natura.", "effects": {"prog": -1}},
    {"id": 33, "question": "Solo le persone eterossessuali dovrebbero poter adottare bambini.", "effects": {"prog": -1}},
    {"id": 34, "question": "La pena di morte dovrebbe esistere per certi crimini.", "effects": {"prog": -1}},
    {"id": 35, "question": "I genitori dovrebbero insegnare ai propri figli a rispettare la disciplina anche con l'uso della forza quando necessario", "effects": {"prog": -1}},
    {"id": 36, "question": "Dovremmo stare tutti solo con i nostri simili", "effects": {"prog": -1}}
]; 
